name = "BigRiverJunbi"
uuid = "6a06b223-7d19-411a-858f-7a319f02fdfd"
authors = ["Abhirath Anand <74202102+theabhirath@users.noreply.github.com>",
           "Greg Farage <faragegr@gmail.com>",
           "Saunak Sen <sen@uthsc.edu>"]
version = "0.0.1-DEV"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
DataFrames = "1.7.0"
Distributions = "0.25.120"
GLM = "1.9.0"
julia = "1.10"
Missings = "1.2.0"
NearestNeighbors = "0.4.21"
PrettyTables = "2.4.0"
Statistics = "1.11.1"
StatsBase = "0.34.5"
